# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d0cf2373ae26a57a14e91415602962afa14d1bc2ba250fb4d84a45d8a29d716dde0a7f3bfda80686f8d2bc190e59536221572646c6503636fee0e5a904e97fb

test:
  secret_key_base: 039047c2598933b9aee10333f768f198a4353f77f99a821283e6c94d2330555d67307905722d2a7b7641f46a26d72daa299a1a1b4d95b2f65b0ea30a486c342d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
